#!/bin/sh
# Tag last commit as 'latest'.

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis"
}

commit_website_files() {
  #git checkout -b gh-pages
  git add .
  git commit -m "Travis build"
}

upload_files() {

  git remote add release https://${GH_TOKEN}@github.com/PawanAhire/ProgressDemo.git
  git push
  
  #git push --quiet --set-upstream origin-pages gh-pages

  #git remote add release https://${GH_TOKEN}@github.com/PawanAhire/ProgressDemo.git
  #git push -d release latest
  #git tag -d latest
  #git tag -a "latest" -m "[Autogenerated] This is the latest version pushed to the master branch."
  #git push release --tags
  
  #git fetch --prune origin
  #git push -d release
  
  #git remote set-url origin https://${GH_TOKEN}@github.com/PawanAhire/ProgressDemo.git
  #git remote add origin "https://${GH_TOKEN}@github.com/PawanAhire/ProgressDemo.git"
  #git remote -v
  #git push -u origin master
  #git push -d release latest
}

setup_git
commit_website_files
upload_files
